### ISSUE TITLE
Name of the agent

### ISSUE THREAD

**Issue by bambuca** [Lambda3/docker-vsts-agent#3]
Would it be possible to add the ability to edit the agent name? Currently it is named by hostname (container id), which is not very readable.

**Comment by giggio** [comment]
The agent name is dependent on the hostname. 
You can set the hostname using docker itself using `--hostname`, or in the `docker-compose` file as well. The build agent code itself does not offer a way to change that. You could as for it at their repo: https://github.com/microsoft/azure-pipelines-agent
I'll close the issue because I don't think there is anything we can do regarding this, but let me know if you think we should reopen.
